### PR TITLE
Add support for tolerations to deployments

### PR DESCRIPTION
**Pull request by zopz**
I requested this functionality here https://github.com/reportportal/kubernetes/issues/129

I don't see any specific contribution guidelines in this repo, so if you have any feedback, let me know and I'm happy to fix.

Love the project, thanks!

### CODE REVIEW

**Review by vutny — APPROVED** [review]
This is cool addition, allows to schedule RP workloads on designated nodes.

**Comment by HardNorth** [comment]
@zopz So sorry, missed that review 😞  Is it still actual? If yes, could you please update the request?

**Comment by HardNorth** [comment]
Merged in #182

**Comment by zopz** [comment]
Sorry, I missed the ping here. Thanks for adding though!

**Pull request closed without merging**
