### PR TITLE
updated version of rabbitmq and postgres

### PR DESCRIPTION
**Pull request by arybkin**

### CODE REVIEW

**Comment by HardNorth** [comment]
We already updated Elastic and Postgres chart versions since they were bugged, e.g. elastic didn't pick up number of replicas. For RabbitMQ I don't see any necessity of the update, since it works well. 
So if you insist on doing that:
1.  provide your motivation
2  update your pull-request with the latest changes from `master`

**Comment by arybkin** [comment]
So basically with rabbitmq and postgress the same issue was appeared. Here some description bellow. So please, update rabbitmq version, and i will close/decline this pr then at all
----------
In the dependencies for postgres and rabbitmq you are using versions – 3.9.1 and 1.18.0. They are using in their charts such api versions that are deprecated and now not actual for last kubernetes. Information for this you can find here - https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/.

**Review by vutny — CHANGES_REQUESTED** [review]
Indeed, this enables the chart to support installation on Kubernetes 1.16 and newer.
There is another bump for MinIO dependency in PR #144 to have complete latest stable K8s coverage. Nothing else is required. I have successfully tested deployment on the 1.17 version.

@arybkin You may consider to update your branch with master, and do bump chart version I guess.

**Comment by avarabyeu** [comment]
Closing this one in favor of #147

**Pull request closed without merging**
